databases:
  - name: "cac-trabajofinal"
    plan: free
    databaseName: bebidas
    user: bebidas_user
services:
  - type: web
    plan: free
    name: cac-trabajofinal
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --config backend/gconfig.py 'backend.app:app'"
    envVars:
      - key: GUNICORN_BIND
        value: "0.0.0.0:8000"
      - key: DB_URL
        fromDatabase:
          name: "cac-trabajofinal"
          property: connectionString