databases:
  - name: "cac-trabajofinal"
    plan: free
    databaseName: sample_s9qf
    user: sample_s9qf_user

services:
  - type: web
    plan: free
    name: flask-sample
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --config src/gconfig.py 'src.app:app'"
    envVars:
      - key: GUNICORN_BIND
        value: "0.0.0.0:8000"
      - key: DB_URL
        fromDatabase:
          name: "flask-sample"
          property: connectionString