databases:
  - name: "cac-trabajofinal"
    plan: free
    databaseName: bebidas
    user: bebidas_user

services:
  - type: web
    plan: free
    name: flask-sample
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --config backend/gconfig.py 'backend.app:app'"
    env:
      - key: GUNICORN_BIND
        value: "0.0.0.0:8000"
      - key: DB_URL
        fromDatabase:
          name: "cac-trabajofinal"
          property: connectionString
    pythonVersion: "3.11.9"
